image_dir_train: 'data/train'
image_dir_test: 'data/test'
output_path: 'saved_model'

n_images_per_dir: 1000
image_size: 256

kernel_size: 3
max_pool: 2
conv_1_filters: 32
conv_2_filters: 64
conv_3_filters: 128
conv_4_filters: 128
conv_5_filters: 64
dropout: 0.2
dense_1_units: 256
dense_2_units: 64
dense_3_units: 2
learning_rate: 0.001
batch_size: 64
val_split: 0.2
num_epochs: 10
random_seed: 0

classification_cutoff: 0.5
min_unsure: 0.5
max_unsure: 0.75

min_precision: 0.3
min_recall: 0.6

best_model: 'model-2022-10-30-12-53-05.h5'

s3_bucket: 'are-you-a-cat'
uploads_key: 'streamlit_uploads'
